/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.TuVanDao;
import Model.TuVan;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class DangKy extends javax.swing.JFrame {
    private String CHoVaTen = "Họ và tên";
    private String CEmail = "Email";
    private String CSoDienThoai = "Số điện thoại";
    private String CBanLa = "Bạn là ?";
    private String CCoso = "Chọn cơ sở gần nhất";
    TuVanDao tvdao = new TuVanDao();
    /**
     * Creates new form DangKy
     */
    public DangKy() {
        initComponents();


        DefaultComboBoxModel cbdtmol = (DefaultComboBoxModel) Combobox_DoiTuong.getModel();
        DefaultComboBoxModel cbcsmol = (DefaultComboBoxModel) Combobox_CoSo.getModel();
        cbdtmol.setSelectedItem("Bạn là?");   
        cbcsmol.setSelectedItem("Chọn cơ sở gần nhất"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextName = new javax.swing.JTextField();
        Combobox_DoiTuong = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        Text_SDT = new javax.swing.JTextField();
        Combobox_CoSo = new javax.swing.JComboBox<>();
        btn_TuVan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        TextName.setText("Họ và tên");
        TextName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextNameFocusLost(evt);
            }
        });
        TextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNameActionPerformed(evt);
            }
        });

        Combobox_DoiTuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Học sinh cấp 2", "Học sinh cấp 3", "Sinh viên năm 1_2", "Sinh viên năm 3_4", "Người đi làm" }));
        Combobox_DoiTuong.setToolTipText("Bạn là?");
        Combobox_DoiTuong.setAutoscrolls(true);
        Combobox_DoiTuong.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Combobox_DoiTuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combobox_DoiTuongActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Giảm ngay tới 2.000.000 VNĐ");

        TextEmail.setText("Email");
        TextEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextEmailFocusLost(evt);
            }
        });

        Text_SDT.setText("Số điện thoại");
        Text_SDT.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                Text_SDTComponentAdded(evt);
            }
        });
        Text_SDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_SDTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Text_SDTFocusLost(evt);
            }
        });

        Combobox_CoSo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Q1", "Q2", "Q3" }));

        btn_TuVan.setBackground(new java.awt.Color(255, 51, 51));
        btn_TuVan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TuVan.setForeground(new java.awt.Color(255, 255, 255));
        btn_TuVan.setText("Tôi cần tư vấn");
        btn_TuVan.setToolTipText("");
        btn_TuVan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TuVanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_TuVan, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextName)
                        .addComponent(Text_SDT, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                        .addComponent(TextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                        .addComponent(Combobox_DoiTuong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Combobox_CoSo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Text_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Combobox_DoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Combobox_CoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_TuVan, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        Combobox_DoiTuong.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Combobox_DoiTuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combobox_DoiTuongActionPerformed
          
    }//GEN-LAST:event_Combobox_DoiTuongActionPerformed

    private void TextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNameActionPerformed

    }//GEN-LAST:event_TextNameActionPerformed

    private void TextNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNameFocusGained
        if (TextName.getText().equals("Họ và tên")){
            TextName.setText("");
            TextName.setForeground(Color.GRAY);
        } else{
            TextName.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_TextNameFocusGained

    private void TextNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNameFocusLost

        if (TextName.getText().equals("")){
            TextName.setText("Họ và tên");
            TextName.setForeground(Color.GRAY); 
        }else {
            TextName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_TextNameFocusLost

    private void Text_SDTComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Text_SDTComponentAdded
        
    }//GEN-LAST:event_Text_SDTComponentAdded

    private void Text_SDTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_SDTFocusGained
        if (Text_SDT.getText().equals("Số điện thoại")){
            Text_SDT.setText("");
            Text_SDT.setForeground(Color.GRAY);
        } else{
            Text_SDT.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_Text_SDTFocusGained

    private void Text_SDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_SDTFocusLost
          if (Text_SDT.getText().equals("")){
            Text_SDT.setText("Số điện thoại");
            Text_SDT.setForeground(Color.GRAY); 
        }else {
            Text_SDT.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_Text_SDTFocusLost

    private void TextEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextEmailFocusGained
        if (TextEmail.getText().equals("Email")){
            TextEmail.setText("");
            TextEmail.setForeground(Color.GRAY);
        } else{
            TextEmail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_TextEmailFocusGained

    private void TextEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextEmailFocusLost
         if (TextEmail.getText().equals("")){
            TextEmail.setText("Email");
            TextEmail.setForeground(Color.GRAY); 
        }else {
            TextEmail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_TextEmailFocusLost

    
    private boolean  checkSDT(String sdt){
        String reg = "^[0-9]{10}$";
        return sdt.matches(reg) ;
    }
    
    private boolean checkGmail(String gmail){
        String reg = "^[a-zA-Z0-9_]+(\\.[a-zA-Z0-9_]+)*@gmail\\.com$";
        return gmail.matches(reg);
    }
    

    
    private void btn_TuVanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TuVanActionPerformed
        String hoTen = TextName.getText();
        String email = TextEmail.getText();
        String sdt = Text_SDT.getText();
        String coSO = (String) Combobox_CoSo.getSelectedItem();
        String doiTuong = (String) Combobox_DoiTuong.getSelectedItem();
        if (hoTen.equals(CHoVaTen)  || coSO.equals(CCoso) || doiTuong.equals(CBanLa)){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin!");
              
            } else if (!checkGmail(email)){
            JOptionPane.showMessageDialog(rootPane, "Email không đúng định dạng");
            }else if (!checkSDT(sdt)){
                JOptionPane.showMessageDialog(rootPane, "SDT không đúng định dạng");
            }else {
                TuVan tv = new TuVan();
                tv.setHoTen(hoTen);
                tv.setEmail(email);
                tv.setSoDienThoai(sdt);
                tv.setCoSO(coSO);
                tv.setDoiTuong(doiTuong);
                tv.setTime(java.time.LocalDateTime.now());
                tv.setTinhTrang("Chưa Tư Vấn");
                for (String s: tvdao.getListSDT()){
                    System.out.println(s);
                }
                System.out.println(tv.getSoDienThoai());
                if (tvdao.getListSDT().contains(tv.getSoDienThoai())){
                    
                    tvdao.CapNhatTuVan(tv);
                }else 
                    tvdao.ThemTuVan(tv);
                
        } 
        getDSTuVan();
        
        
    }//GEN-LAST:event_btn_TuVanActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
          setDefaultCloseOperation(QLTUVAN.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKy().setVisible(true);
                
            }
        });
        

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combobox_CoSo;
    private javax.swing.JComboBox<String> Combobox_DoiTuong;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextName;
    private javax.swing.JTextField Text_SDT;
    private javax.swing.JButton btn_TuVan;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void getDSTuVan() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
